/**
 * Config loader for Node.js backend services.
 *
 * Reads jarvis-file.config.json from the same directory as the
 * calling script. This JSON file is generated by the CLI from
 * the same values as the browser config (jarvis-file.config.js).
 */

"use strict";

const fs = require("fs");

const CONFIG_FILENAME = "jarvis-file.config.json";

/**
 * Load and validate the Jarvis File config.
 * @returns {object} Parsed config object
 */
function loadConfig() {
   const configPath = __dirname + "/../" + CONFIG_FILENAME;

   if (!fs.existsSync(configPath)) {
      throw new Error(
         `Config file not found: ${CONFIG_FILENAME}. ` +
         "Run create-jarvis-file to generate the project."
      );
   }

   const raw = fs.readFileSync(configPath, "utf-8");
   const config = JSON.parse(raw);

   // Validate required fields
   const required = [
      "project.slug",
      "firebase.projectId",
      "assistant.name",
      "assistant.model",
   ];

   for (const key of required) {
      const parts = key.split(".");
      let val = config;
      for (const part of parts) {
         val = val && val[part];
      }
      if (!val) {
         throw new Error(`Missing required config field: ${key}`);
      }
   }

   return config;
}

module.exports = { loadConfig };
