/**
 * Project file generator.
 *
 * Takes a pre-validated absolute directory path and config object,
 * then scaffolds the complete Jarvis File project. The projectDir
 * parameter is validated by validate-path.js before reaching this module.
 */

"use strict";

const fs = require("fs/promises");
const { compileRules } = require("./rules-compiler");
const { compilePersona } = require("./persona-compiler");

const SEP = "/";

/**
 * Build a file path under the project directory using only known-safe
 * subdirectory names. projectDir is pre-validated by validate-path.js.
 * @param {string} base - Pre-validated absolute project directory
 * @param {...string} segments - Hardcoded subdirectory/file names
 * @returns {string} Absolute file path
 */
function filePath(base, ...segments) {
   return base + SEP + segments.join(SEP);
}

/**
 * Generate the full project directory from config.
 * @param {string} projectDir - Pre-validated absolute path (from validate-path.js)
 * @param {object} config - Complete config object from buildConfig()
 */
async function generateProject(projectDir, config) {
   // Create directory structure
   await fs.mkdir(filePath(projectDir, "js"), { recursive: true });
   await fs.mkdir(filePath(projectDir, "css"), { recursive: true });
   await fs.mkdir(filePath(projectDir, "jarvis"), { recursive: true });
   await fs.mkdir(filePath(projectDir, "scripts"), { recursive: true });

   // Generate config files
   await writeConfigJs(filePath(projectDir, "jarvis-file.config.js"), config);
   await writeConfigJson(filePath(projectDir, "jarvis", "jarvis-file.config.json"), config);
   await writeDocsManifest(filePath(projectDir, "docs-manifest.json"), config);
   await writeVersionsJson(filePath(projectDir, "versions.json"), config);

   // Generate Firebase files
   await writeFirebaseRc(filePath(projectDir, ".firebaserc"), config);
   await writeFirebaseJson(filePath(projectDir, "firebase.json"));
   await fs.writeFile(filePath(projectDir, "firestore.rules"), compileRules(config));
   await writeFirestoreIndexes(filePath(projectDir, "firestore.indexes.json"));

   // Copy framework JS and CSS from jarvis-file-core
   await copyFrameworkFiles(filePath(projectDir, "js"), filePath(projectDir, "css"));

   // Generate HTML templates
   await generateTemplates(projectDir, config);

   // Generate backend files
   await generateBackend(filePath(projectDir, "jarvis"), config);
   await fs.writeFile(filePath(projectDir, "jarvis", "PERSONA.md"), compilePersona(config));

   // Generate scripts
   await generateScripts(filePath(projectDir, "scripts"));

   // Generate gitignore
   await writeGitignore(filePath(projectDir, ".gitignore"));

   // Generate favicon
   await writeFavicon(filePath(projectDir, "favicon.svg"), config);
}

// -- File writers (stubs for Phase 2 implementation) --

async function writeConfigJs(dest, config) {
   const content = `// jarvis-file.config.js -- Single source of truth
// Generated by create-jarvis-file

window.JF = ${JSON.stringify(config, null, 2)};
`;
   await fs.writeFile(dest, content);
}

async function writeConfigJson(dest, config) {
   await fs.writeFile(dest, JSON.stringify(config, null, 2));
}

async function writeDocsManifest(dest, config) {
   const manifest = {
      documents: config.docs.map((doc) => ({
         ...doc,
         editable: true,
      })),
      protectedFiles: [
         "js/auth-gate.js",
         "js/comments.js",
         "js/jarvis-chat.js",
         "js/search.js",
         "js/config-loader.js",
         "jarvis/jarvis.js",
         "jarvis/change-processor.js",
         "firestore.rules",
         "firebase.json",
      ],
   };
   await fs.writeFile(dest, JSON.stringify(manifest, null, 2));
}

async function writeVersionsJson(dest, config) {
   const versions = [
      {
         version: config.project.version,
         date: new Date().toISOString().split("T")[0],
         label: "Initial version",
         current: true,
      },
   ];
   await fs.writeFile(dest, JSON.stringify(versions, null, 2));
}

async function writeFirebaseRc(dest, config) {
   const rc = {
      projects: {
         default: config.firebase.projectId,
      },
   };
   await fs.writeFile(dest, JSON.stringify(rc, null, 2));
}

async function writeFirebaseJson(dest) {
   const fbConfig = {
      hosting: {
         public: ".",
         ignore: [
            "firebase.json",
            "**/node_modules/**",
            "jarvis/**",
            "scripts/**",
            ".gitignore",
            "package.json",
            "docs-manifest.json",
         ],
         headers: [
            {
               source: "**/*.html",
               headers: [
                  { key: "Cache-Control", value: "no-cache" },
               ],
            },
         ],
      },
      firestore: {
         rules: "firestore.rules",
         indexes: "firestore.indexes.json",
      },
   };
   await fs.writeFile(dest, JSON.stringify(fbConfig, null, 2));
}

async function writeFirestoreIndexes(dest) {
   const indexes = {
      indexes: [
         {
            collectionGroup: "_comments",
            queryScope: "COLLECTION",
            fields: [
               { fieldPath: "documentId", order: "ASCENDING" },
               { fieldPath: "createdAt", order: "ASCENDING" },
            ],
         },
      ],
      fieldOverrides: [],
   };
   await fs.writeFile(dest, JSON.stringify(indexes, null, 2));
}

async function copyFrameworkFiles(_jsDir, _cssDir) {
   // Phase 2: Copy from jarvis-file-core package
}

async function generateTemplates(_projectDir, _config) {
   // Phase 3: Generate HTML files from starter templates
}

async function generateBackend(_jarvisDir, _config) {
   // Phase 2: Generate jarvis.js and change-processor.js
}

async function generateScripts(_scriptsDir) {
   // Phase 2: Generate deploy.sh and start-jarvis.sh
}

async function writeGitignore(dest) {
   const content = `node_modules/
.env
service-account-key.json
.firebase/
*.log
.DS_Store
`;
   await fs.writeFile(dest, content);
}

async function writeFavicon(dest, config) {
   const primary = config.theme.primaryColor;
   const accent = config.theme.accentColor;
   const letter = config.project.logoLetter;
   const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <defs>
    <linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:${primary}"/>
      <stop offset="100%" style="stop-color:${accent}"/>
    </linearGradient>
  </defs>
  <rect width="100" height="100" rx="20" fill="url(#g)"/>
  <text x="50" y="68" font-family="Inter,sans-serif" font-size="60" font-weight="700" fill="white" text-anchor="middle">${letter}</text>
</svg>`;
   await fs.writeFile(dest, svg);
}

module.exports = { generateProject };
