/**
 * Jarvis -- Comment Monitor + Chat Responder
 *
 * Watches Firestore for new comments and chat messages, generates
 * contextual AI responses using Claude, and posts them back.
 *
 * Configuration loaded from jarvis-file.config.json (generated by CLI).
 *
 * Phase 1 implementation: Refactor from Praesidium2 jarvis.js to read
 * all values from config instead of hardcoded constants.
 */

"use strict";

const { loadConfig } = require("./lib/config");
const { initFirestore } = require("./lib/firestore");
const { createClient } = require("./lib/anthropic");

async function main() {
   const config = loadConfig();

   const db = initFirestore(config);
   const claude = createClient(config);

   const commentsCollection = config.project.slug + "_comments";
   const chatCollection = config.project.slug + "_jarvis_chats";

   console.log(`[${config.assistant.name}] Watching ${commentsCollection} and ${chatCollection}`);
   console.log(`[${config.assistant.name}] Model: ${config.assistant.model}`);
   console.log(`[${config.assistant.name}] Reply delay: ${config.assistant.replyDelayMs}ms`);

   // TODO: Phase 1 -- implement comment listener
   // TODO: Phase 1 -- implement chat listener
   // TODO: Phase 1 -- implement context reader (extract section text from HTML)
   // TODO: Phase 1 -- implement response generator
}

main().catch((err) => {
   console.error("Fatal:", err.message);
   process.exit(1);
});
